### ISSUE TITLE
Adding an option to show the "Publish" meta box

### ISSUE THREAD

**Issue by BoweFrankema** [intraxia/wp-gistpen#35]
Hi James,

Thanks for the awesome plugin, I'm currently playing around with it. For my needs I'm extending the Gistpen CPT by adding a few taxonomies to it (which are shared with other CPT). This is all working fine but it's currently not possible to save the taxonomy values since your (very fancy!) "Update Gistpen" button bypasses the regular Publish action. I've solved this by simply uncommenting the line that disables the post meta box, but maybe this should be an option or filter for people that might want to do the same?

**Comment by mAAdhaTTah** [comment]
This is probably going to be more difficult than first thought, since the API will need to support it, and it will need to be hooked into the JS to send the data. It might be easy to provide an action to hook into to save Zips to additional taxonomies on the back-end; the data hook stuff on the front-end will be a bit more complicated.

**Comment by mAAdhaTTah** [comment]
This is not going to be feasible in 1.0.0 yet, but I'll keep it in mind for a future enhancement. There's more to it now than simply enabling a meta box; the entire lifecycle is API-driven, rather than using the traditional WordPress hooks, so we've got to figure out a WordPress-y way of enabling this. Will definitely be keeping an eye on how Gutenberg solves this problem, as they're going to run into similar problems.

**Comment by mAAdhaTTah** [comment]
I don't think this is something I'd be implementing myself, because I don't know how I would use it. If you or anyone else is interested in making them extendable in some way, I'd be open to a proposal on how an API like that would work, or how we could take advantage of WordPress's built-in capabilities. Because it's not my use case, I'm not sure how this even _should_ work, and since I'm not going to work on it myself, I'm going to close this.

If you have a proposal, I'd be open to it, so feel free to open an issue about it.
